// Alle UI- und Berichtstexte zentral (Deutsch). Weitere Sprachen später als texte/en.ts.
export const de = {
  app: {
    name: 'Taste Report',
    untertitel: 'Bierverkostungen erfassen und auswerten',
  },
  allgemein: {
    zurueck: 'Zurück',
    abbrechen: 'Abbrechen',
    speichern: 'Speichern',
    loeschen: 'Löschen',
    bearbeiten: 'Bearbeiten',
    pflichtfeld: 'Pflichtfeld',
    einstellungen: 'Einstellungen',
  },
  liste: {
    titel: 'Meine Tastings',
    neu: '+ Neues Tasting',
    leerTitel: 'Noch kein Tasting',
    leerText: 'Lege dein erstes Tasting an, zum Beispiel für das nächste Bierfestival.',
    verkoster: 'Verkoster',
    biere: (n: number) => (n === 1 ? '1 Bier' : `${n} Biere`),
    vorgemerkt: (n: number) => `${n} vorgemerkt`,
  },
  tastingForm: {
    titelNeu: 'Neues Tasting',
    titelBearbeiten: 'Tasting bearbeiten',
    name: 'Name',
    namePlatzhalter: 'z. B. Bierfestival Bremen 2026',
    untertitel: 'Untertitel (optional)',
    datumVon: 'Datum von',
    datumBis: 'Datum bis (optional)',
    ort: 'Ort (optional)',
    verkoster: 'Verkoster',
    fehlerDatumBis: 'Das Enddatum liegt vor dem Startdatum.',
    loeschenTitel: 'Tasting löschen',
    loeschenFrage: (name: string) =>
      `„${name}“ mit allen Bieren und Fotos wirklich löschen? Das lässt sich nicht rückgängig machen. Ein ZIP-Backup schützt vor Datenverlust.`,
  },
  uebersicht: {
    getraenke: 'Getränke',
    auswertung: 'Auswertung',
    neuesBier: '+ Bier',
    leerTitel: 'Noch kein Bier',
    leerText: 'Tippe auf „+ Bier“, sobald du das erste Bier probierst oder vormerkst.',
    merkliste: 'Merkliste',
    merklisteInfo: (n: number) => `${n} vorgemerkt, noch nicht probiert`,
    nachHersteller: 'Nach Hersteller',
    alleZuklappen: 'Alle zuklappen',
    alleAufklappen: 'Alle aufklappen',
    vorgemerkt: 'vorgemerkt',
    nichtBewertet: 'noch nicht bewertet',
  },
  auswertung: {
    biere: 'Biere',
    hersteller: 'Hersteller',
    durchschnitt: 'Ø Wert',
    sieger: 'Bier des Festivals',
    siegerAutomatisch: 'automatisch das beste',
    siegerGewaehlt: 'von dir gewählt',
    aendern: 'Ändern',
    siegerWaehlen: 'Bier des Festivals wählen',
    automatisch: 'Automatisch (bestes Bier)',
    rangliste: 'Rangliste',
    herstellerDurchschnitt: 'Durchschnitt je Hersteller',
    fazit: 'Fazit',
    fazitPlatzhalter: 'Dein Festival in einem Absatz …',
    gespeichert: '✓ Fazit gespeichert',
    keineBewertung: 'Noch kein bewertetes Bier. Sobald du Biere bewertest, erscheinen hier Rangliste und Durchschnitte.',
    schliessen: 'Schließen',
    bewerteteBiere: (n: number) => (n === 1 ? '1 bewertetes Bier' : `${n} bewertete Biere`),
  },
  pdf: {
    berichtVon: 'Verkostungsbericht von',
    fazit: 'Fazit',
    siegerLabel: 'Bier des Festivals',
    top5: 'Top 5',
    fortsetzung: '(Fortsetzung)',
    seite: 'Seite',
    von: 'von',
  },
  excel: {
    blatt: 'Getränke',
    tasting: 'Tasting',
    untertitel: 'Untertitel',
    datum: 'Datum',
    ort: 'Ort',
    verkoster: 'Verkoster',
    spalten: ['Hersteller', 'Standort', 'Getränk', 'Stil', 'Bewertung', 'Alkohol (% Vol.)', 'Menge (L)', 'Preis (€)', 'Notiz', 'Zustand', 'probiert am'],
    probiert: 'probiert',
    vorgemerkt: 'vorgemerkt',
  },
  export: {
    titel: 'Exportieren',
    pdfTitel: 'PDF-Bericht',
    pdfText: 'Gestaltet mit Cover, Fazit, Top 5 und einer Seite je Hersteller',
    fotos: 'Fotos einbeziehen',
    nurBewertete: 'Nur bewertete Biere',
    erstellen: 'Bericht erstellen',
    schliessen: 'Schließen',
    arbeitet: 'Bericht wird erstellt …',
    fortschritt: (fertig: number, gesamt: number) => `${fertig} von ${gesamt} Bieren`,
    vorschau: 'Vorschau',
    teilen: 'Teilen / Speichern',
    seiten: (n: number) => (n === 1 ? '1 Seite' : `${n} Seiten`),
    fehler: 'Der Bericht konnte nicht erstellt werden.',
    nochmal: 'Noch einmal versuchen',
    excelTitel: 'Excel-Datenliste',
    excelText: 'Eine Tabelle mit allen Bieren, zum Sortieren und Filtern',
    excelErstellen: 'Excel erstellen und teilen',
    excelArbeitet: 'Tabelle wird erstellt …',
    excelFehler: 'Die Tabelle konnte nicht erstellt werden.',
  },
  backup: {
    titel: 'Backup (ZIP)',
    text: 'Sichert dieses Tasting mit allen Bieren und Fotos, zum Wiederherstellen auf diesem oder einem anderen Gerät',
    textAlle: 'Sichert alle Tastings mit Bieren, Fotos und Bierstilen in einer Datei',
    erstellen: 'Backup erstellen',
    arbeitet: 'Backup wird erstellt …',
    fortschritt: (fertig: number, gesamt: number) => `Foto ${fertig} von ${gesamt}`,
    fertig: (tastings: number, biere: number, fotos: number, mb: string) =>
      `${tastings === 1 ? '1 Tasting' : `${tastings} Tastings`}, ${biere === 1 ? '1 Bier' : `${biere} Biere`}, ${fotos === 1 ? '1 Foto' : `${fotos} Fotos`} · ${mb} MB`,
    teilen: 'Teilen / Speichern',
    teilenHinweis: 'Speichere die Datei zum Beispiel in „Dateien“ oder iCloud Drive. Erst dann gilt das Tasting als gesichert.',
    gesichert: '✓ Gesichert',
    nochmal: 'Noch einmal sichern',
    fehler: 'Das Backup konnte nicht erstellt werden.',
    fotosFehlen: (n: number) => `${n === 1 ? '1 Foto' : `${n} Fotos`} ließ${n === 1 ? '' : 'en'} sich nicht lesen und fehl${n === 1 ? 't' : 'en'} im Backup.`,
    kopieSuffix: ' (Kopie)',
    zuletzt: (zeit: string) => `Zuletzt gesichert: ${zeit}`,
    nochNie: 'Noch nicht gesichert',
    gesamtZuletzt: 'Alles gesichert',
    hinweisTitel: 'Zeit für ein Backup',
    hinweisText: 'Neue Biere oder dein Fazit sind noch nicht gesichert. Die Daten liegen nur auf diesem Gerät.',
    hinweisJetzt: 'Jetzt sichern',
    hinweisSchliessen: 'Hinweis schließen',
    startTitel: 'Deine Daten liegen nur auf diesem Gerät',
    startText: 'Es gibt kein Konto und keine Cloud. Sichere wichtige Tastings regelmäßig als Backup (⇪ im Tasting oder unter ⚙ Einstellungen).',
    startOk: 'Verstanden',
  },
  import: {
    knopf: 'Backup einspielen …',
    titel: 'Backup einspielen',
    lesen: 'Datei wird geprüft …',
    inhalt: (tastings: number, biere: number, fotos: number) =>
      `Das Backup enthält ${tastings === 1 ? '1 Tasting' : `${tastings} Tastings`}, ${biere === 1 ? '1 Bier' : `${biere} Biere`} und ${fotos === 1 ? '1 Foto' : `${fotos} Fotos`}.`,
    kollision: (n: number) => (n === 1 ? 'Ein Tasting ist schon auf diesem Gerät.' : `${n} Tastings sind schon auf diesem Gerät.`),
    kollisionHinweis: 'Ersetzen überschreibt Änderungen, die seit dem Backup gemacht wurden. Als Kopie bleibt das vorhandene Tasting unberührt.',
    ersetzen: 'Vorhandene ersetzen',
    kopie: 'Als Kopie anlegen',
    einspielen: 'Einspielen',
    abbrechen: 'Abbrechen',
    arbeitet: 'Backup wird eingespielt …',
    fertig: (tastings: number, biere: number, fotos: number) =>
      `✓ ${tastings === 1 ? '1 Tasting' : `${tastings} Tastings`} mit ${biere === 1 ? '1 Bier' : `${biere} Bieren`} und ${fotos === 1 ? '1 Foto' : `${fotos} Fotos`} eingespielt.`,
    neueStile: (n: number) => `${n === 1 ? '1 neuer Bierstil wurde' : `${n} neue Bierstile wurden`} ergänzt.`,
    fehlerFormat: 'Das ist kein gültiges Taste-Report-Backup.',
    fehlerVersion: 'Dieses Backup stammt aus einer neueren Version der App. Bitte die App aktualisieren.',
    fehlerLeer: 'Das Backup enthält keine Tastings.',
    fehlerAllgemein: 'Das Backup konnte nicht eingespielt werden. Es wurde nichts verändert.',
    schliessen: 'Schließen',
  },
  regler: {
    titel: 'Bewertung',
    weniger: 'Bewertung verringern',
    mehr: 'Bewertung erhöhen',
    zuruecksetzen: 'Zurücksetzen',
    nichtBewertet: 'Noch nicht bewertet',
    hinweis: 'Ziehen oder +/−',
  },
  getraenkForm: {
    titelNeu: 'Neues Bier',
    nr: (i: number, n: number) => `Bier ${i} von ${n}`,
    vorheriges: 'Vorheriges Bier',
    naechstes: 'Nächstes Bier',
    vorgemerkt: 'Vorgemerkt',
    probiert: 'Probiert ✓',
    hersteller: 'Hersteller',
    herstellerPlatzhalter: 'z. B. Brau Kru',
    standort: 'Stand / Halle (optional)',
    name: 'Name des Biers',
    stil: 'Stil',
    alleStile: 'alle …',
    weniger: 'weniger',
    bewertung: 'Bewertung',
    notiz: 'Verkostungsnotiz',
    notizPlatzhalter: 'Aussehen, Geruch, Geschmack, Abgang …',
    kopieren: 'kopieren',
    kopiert: 'kopiert ✓',
    mehr: 'Mehr Angaben (Alkohol, Menge, Preis)',
    abv: 'Alkohol (% Vol.)',
    menge: 'Menge (L)',
    preis: 'Preis (€)',
    preisHinweis: 'Preis für die angegebene Menge',
    unvollstaendig: 'Hersteller und Name ausfüllen, dann wird automatisch gespeichert.',
    unvollstaendigVerlassen: 'Ohne Hersteller und Name wird das Bier nicht gespeichert (auch die Fotos nicht). Trotzdem verlassen?',
    gespeichert: '✓ Automatisch gespeichert',
    speichert: 'Speichert …',
    fehler: 'Speichern fehlgeschlagen. Bitte noch einmal versuchen.',
    loeschen: 'Bier löschen …',
    loeschenFrage: (name: string) => `„${name}“ wirklich löschen?`,
  },
  fotos: {
    titel: 'Fotos',
    titelHinweis: 'das erste ist das Titelbild',
    hinzufuegen: 'Foto hinzufügen',
    titelbild: '★ Titel',
    verarbeiten: 'Foto wird verarbeitet …',
    fehler: 'Das Foto konnte nicht verarbeitet werden.',
    schliessen: 'Schließen',
    alsTitelbild: 'Als Titelbild',
    loeschen: 'Foto löschen',
    loeschenFrage: 'Dieses Foto wirklich löschen?',
    nichtLesbar: 'Foto nicht lesbar',
    cover: 'Cover-Bild (optional)',
    coverAendern: 'Cover ändern',
    coverWaehlen: 'Cover-Bild wählen',
    coverEntfernen: 'Cover entfernen',
  },
  einstellungen: {
    titel: 'Einstellungen',
    verkoster: 'Verkoster (Standard)',
    verkosterHinweis: 'Wird bei neuen Tastings vorbelegt und kann dort geändert werden.',
    stile: 'Bierstile',
    stilNeu: 'Neuer Stil',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'aktiv',
    inaktiv: 'inaktiv',
    nachOben: 'nach oben',
    nachUnten: 'nach unten',
    stileHinweis: 'Inaktive Stile erscheinen bei neuen Bieren nicht mehr. Bestehende Biere behalten ihren Stil.',
    sicherungTitel: 'Datensicherung',
    datenTitel: 'Speicher und Offline',
    speicherPersistiertJa: 'Speicher dauerhaft geschützt',
    speicherPersistiertNein: 'Speicher nicht dauerhaft geschützt',
    speicherVerwendet: (verwendet: string, verfuegbar: string) => `${verwendet} MB von ${verfuegbar} MB verwendet`,
    speicherHinweis:
      'Die Daten liegen nur auf diesem Gerät. Wird das App-Symbol vom Homescreen gelöscht oder werden die Website-Daten gelöscht, sind sie verloren.',
    offlineBereit: 'Offline-Speicher bereit',
    offlineLaedt: 'Offline-Speicher wird vorbereitet …',
    online: 'Online',
    offline: 'Offline',
    installiert: 'Installiert (Homescreen)',
    imBrowser: 'Im Browser',
    version: 'Stand',
  },
} as const;
