// Alle UI- und Berichtstexte zentral (Deutsch). Weitere Sprachen später als texte/en.ts.
export const de = {
  app: {
    name: 'Taste Report',
    untertitel: 'Bierverkostungen erfassen und auswerten',
  },
  allgemein: {
    zurueck: 'Zurück',
    abbrechen: 'Abbrechen',
    speichern: 'Speichern',
    loeschen: 'Löschen',
    bearbeiten: 'Bearbeiten',
    pflichtfeld: 'Pflichtfeld',
    einstellungen: 'Einstellungen',
  },
  liste: {
    titel: 'Meine Tastings',
    neu: '+ Neues Tasting',
    leerTitel: 'Noch kein Tasting',
    leerText: 'Lege dein erstes Tasting an, zum Beispiel für das nächste Bierfestival.',
    verkoster: 'Verkoster',
    biere: (n: number) => (n === 1 ? '1 Bier' : `${n} Biere`),
    vorgemerkt: (n: number) => `${n} vorgemerkt`,
  },
  tastingForm: {
    titelNeu: 'Neues Tasting',
    titelBearbeiten: 'Tasting bearbeiten',
    name: 'Name',
    namePlatzhalter: 'z. B. Bierfestival Bremen 2026',
    untertitel: 'Untertitel (optional)',
    datumVon: 'Datum von',
    datumBis: 'Datum bis (optional)',
    ort: 'Ort (optional)',
    verkoster: 'Verkoster',
    fehlerDatumBis: 'Das Enddatum liegt vor dem Startdatum.',
    loeschenTitel: 'Tasting löschen',
    loeschenFrage: (name: string) =>
      `„${name}“ mit allen Bieren und Fotos wirklich löschen? Das lässt sich nicht rückgängig machen. Ein ZIP-Backup schützt vor Datenverlust.`,
  },
  uebersicht: {
    getraenke: 'Getränke',
    auswertung: 'Auswertung',
    auswertungFolgt: 'Die Auswertung mit Rangliste und Fazit folgt in Phase 5.',
    neuesBier: '+ Bier',
    leerTitel: 'Noch kein Bier',
    leerText: 'Tippe auf „+ Bier“, sobald du das erste Bier probierst oder vormerkst.',
    merkliste: 'Merkliste',
    merklisteInfo: (n: number) => `${n} vorgemerkt, noch nicht probiert`,
    nachHersteller: 'Nach Hersteller',
    alleZuklappen: 'Alle zuklappen',
    alleAufklappen: 'Alle aufklappen',
    vorgemerkt: 'vorgemerkt',
    nichtBewertet: 'noch nicht bewertet',
  },
  regler: {
    titel: 'Bewertung',
    weniger: 'Bewertung verringern',
    mehr: 'Bewertung erhöhen',
    zuruecksetzen: 'Zurücksetzen',
    nichtBewertet: 'Noch nicht bewertet',
    hinweis: 'Ziehen oder +/−',
  },
  getraenkForm: {
    titelNeu: 'Neues Bier',
    nr: (i: number, n: number) => `Bier ${i} von ${n}`,
    vorheriges: 'Vorheriges Bier',
    naechstes: 'Nächstes Bier',
    vorgemerkt: 'Vorgemerkt',
    probiert: 'Probiert ✓',
    hersteller: 'Hersteller',
    herstellerPlatzhalter: 'z. B. Brau Kru',
    standort: 'Stand / Halle (optional)',
    name: 'Name des Biers',
    stil: 'Stil',
    alleStile: 'alle …',
    weniger: 'weniger',
    bewertung: 'Bewertung',
    notiz: 'Verkostungsnotiz',
    notizPlatzhalter: 'Aussehen, Geruch, Geschmack, Abgang …',
    kopieren: 'kopieren',
    kopiert: 'kopiert ✓',
    mehr: 'Mehr Angaben (Alkohol, Menge, Preis)',
    abv: 'Alkohol (% Vol.)',
    menge: 'Menge (L)',
    preis: 'Preis (€)',
    preisHinweis: 'Preis für die angegebene Menge',
    unvollstaendig: 'Hersteller und Name ausfüllen, dann wird automatisch gespeichert.',
    unvollstaendigVerlassen: 'Ohne Hersteller und Name wird das Bier nicht gespeichert (auch die Fotos nicht). Trotzdem verlassen?',
    gespeichert: '✓ Automatisch gespeichert',
    speichert: 'Speichert …',
    fehler: 'Speichern fehlgeschlagen. Bitte noch einmal versuchen.',
    loeschen: 'Bier löschen …',
    loeschenFrage: (name: string) => `„${name}“ wirklich löschen?`,
  },
  fotos: {
    titel: 'Fotos',
    titelHinweis: 'das erste ist das Titelbild',
    hinzufuegen: 'Foto hinzufügen',
    titelbild: '★ Titel',
    verarbeiten: 'Foto wird verarbeitet …',
    fehler: 'Das Foto konnte nicht verarbeitet werden.',
    schliessen: 'Schließen',
    alsTitelbild: 'Als Titelbild',
    loeschen: 'Foto löschen',
    loeschenFrage: 'Dieses Foto wirklich löschen?',
    nichtLesbar: 'Foto nicht lesbar',
    cover: 'Cover-Bild (optional)',
    coverAendern: 'Cover ändern',
    coverWaehlen: 'Cover-Bild wählen',
    coverEntfernen: 'Cover entfernen',
  },
  einstellungen: {
    titel: 'Einstellungen',
    verkoster: 'Verkoster (Standard)',
    verkosterHinweis: 'Wird bei neuen Tastings vorbelegt und kann dort geändert werden.',
    stile: 'Bierstile',
    stilNeu: 'Neuer Stil',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'aktiv',
    inaktiv: 'inaktiv',
    nachOben: 'nach oben',
    nachUnten: 'nach unten',
    stileHinweis: 'Inaktive Stile erscheinen bei neuen Bieren nicht mehr. Bestehende Biere behalten ihren Stil.',
    datenTitel: 'Speicher und Offline',
    speicherPersistiertJa: 'Speicher dauerhaft geschützt',
    speicherPersistiertNein: 'Speicher nicht dauerhaft geschützt',
    speicherVerwendet: (verwendet: string, verfuegbar: string) => `${verwendet} MB von ${verfuegbar} MB verwendet`,
    speicherHinweis:
      'Die Daten liegen nur auf diesem Gerät. Wird das App-Symbol vom Homescreen gelöscht oder werden die Website-Daten gelöscht, sind sie verloren.',
    offlineBereit: 'Offline-Speicher bereit',
    offlineLaedt: 'Offline-Speicher wird vorbereitet …',
    online: 'Online',
    offline: 'Offline',
    installiert: 'Installiert (Homescreen)',
    imBrowser: 'Im Browser',
    version: 'Stand',
  },
} as const;
