// Alle UI- und Berichtstexte zentral (Deutsch). Weitere Sprachen später als texte/en.ts.
export const de = {
  app: {
    name: 'Taste Report',
    untertitel: 'Bierverkostungen erfassen und auswerten',
  },
  allgemein: {
    zurueck: 'Zurück',
    abbrechen: 'Abbrechen',
    speichern: 'Speichern',
    loeschen: 'Löschen',
    bearbeiten: 'Bearbeiten',
    pflichtfeld: 'Pflichtfeld',
    einstellungen: 'Einstellungen',
  },
  liste: {
    titel: 'Meine Tastings',
    neu: '+ Neues Tasting',
    leerTitel: 'Noch kein Tasting',
    leerText: 'Lege dein erstes Tasting an, zum Beispiel für das nächste Bierfestival.',
    verkoster: 'Verkoster',
    biere: (n: number) => (n === 1 ? '1 Bier' : `${n} Biere`),
    vorgemerkt: (n: number) => `${n} vorgemerkt`,
  },
  tastingForm: {
    titelNeu: 'Neues Tasting',
    titelBearbeiten: 'Tasting bearbeiten',
    name: 'Name',
    namePlatzhalter: 'z. B. Bierfestival Bremen 2026',
    untertitel: 'Untertitel (optional)',
    datumVon: 'Datum von',
    datumBis: 'Datum bis (optional)',
    ort: 'Ort (optional)',
    verkoster: 'Verkoster',
    fehlerDatumBis: 'Das Enddatum liegt vor dem Startdatum.',
    loeschenTitel: 'Tasting löschen',
    loeschenFrage: (name: string) =>
      `„${name}“ mit allen Bieren und Fotos wirklich löschen? Das lässt sich nicht rückgängig machen. Ein ZIP-Backup schützt vor Datenverlust.`,
  },
  uebersicht: {
    getraenke: 'Getränke',
    auswertung: 'Auswertung',
    platzhalter: 'Hier erscheinen die Biere dieses Tastings. Die Erfassung folgt in Phase 3.',
  },
  einstellungen: {
    titel: 'Einstellungen',
    verkoster: 'Verkoster (Standard)',
    verkosterHinweis: 'Wird bei neuen Tastings vorbelegt und kann dort geändert werden.',
    stile: 'Bierstile',
    stilNeu: 'Neuer Stil',
    hinzufuegen: 'Hinzufügen',
    aktiv: 'aktiv',
    inaktiv: 'inaktiv',
    nachOben: 'nach oben',
    nachUnten: 'nach unten',
    stileHinweis: 'Inaktive Stile erscheinen bei neuen Bieren nicht mehr. Bestehende Biere behalten ihren Stil.',
    datenTitel: 'Speicher und Offline',
    speicherPersistiertJa: 'Speicher dauerhaft geschützt',
    speicherPersistiertNein: 'Speicher nicht dauerhaft geschützt',
    speicherVerwendet: (verwendet: string, verfuegbar: string) => `${verwendet} MB von ${verfuegbar} MB verwendet`,
    speicherHinweis:
      'Die Daten liegen nur auf diesem Gerät. Wird das App-Symbol vom Homescreen gelöscht oder werden die Website-Daten gelöscht, sind sie verloren.',
    offlineBereit: 'Offline-Speicher bereit',
    offlineLaedt: 'Offline-Speicher wird vorbereitet …',
    online: 'Online',
    offline: 'Offline',
    installiert: 'Installiert (Homescreen)',
    imBrowser: 'Im Browser',
    version: 'Stand',
  },
} as const;
